name: notify

on:
  push:
    branches: ['release']

jobs:
  build:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Pull
        run: docker pull docker.pkg.github.com/uta8a/onepaas.slack-notify/onepaas-slack-notify:latest
      - name: Notify
        run: docker run -v $PWD:/work docker.pkg.github.com/uta8a/onepaas.slack-notify/onepaas-slack-notify sh -c "cd /work && HICODER_ONEPAAS_SLACK_TOKEN=${{ secrets.HICODER_ONEPAAS_SLACK_TOKEN }} onepaas-slack-notify"
